var Name = "Urooj";
// False 
console.log("Test 1: My Name is Ali");
console.log(Name == "Ali");
var country = "Pakistan";
console.log("\nTest 2: Pakistan is the neighbour of India");
console.log(country == "India");
var ID = "20211-30064";
console.log("\nTest 3: My ID is 20211-5656");
console.log(ID == "20211-5656");
var laptop = "Dell";
console.log("\nTest 4: I have a Mac book");
console.log(laptop == "Mac book");
var Program = "ACF";
console.log("\n Test 5: My Program is BBA");
console.log(Program == "BBA");
//True
var city = "Karachi";
console.log("\n Test 6: I live in Karachi");
console.log(city == "Karachi");
var fruit = "apple";
console.log("\n Test 7:apply is my fav Fruit ");
console.log(fruit == "apple");
var book = "History";
console.log("/n Test 8: I donot Like History Books");
console.log(book == "History");
var course = "IT";
console.log("/n Test 9: I am learning the course IT");
console.log(course == "IT");
var number = 35;
console.log("/n Test 10: 35 is an Odd Number");
console.log(number == 35);
