let num1:number=3
let num2:number=9
//Addtion Operation
console.log("Addition", num1+num2);
//Subtraction Operation
console.log("Subtraction", num1-num2);
//Multiplication Operation
console.log("Multiplication", num1*num2);
//Division Operation
console.log("Division", num1%num2);